// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixpcilpiysuakwhkvqiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4cGNpbHBpeXN1YWt3aGt2cWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTU0NTksImV4cCI6MjA2NDkzMTQ1OX0.VcPq6VHvGnOov_qFx-AzP3C7pVn1E2zccSRI61ULeGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);